---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: todo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kube/manifests/todo
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra

