---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: drone
  namespace: drone
spec:
  interval: 5m3s
  path: ./kube/manifests/drone
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  validation: client

