---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gifinator
  namespace: flux-system
spec:
  interval: 3m5s
  path: ./kube/manifests/gifinator
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  validation: client

