---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: democratic-csi
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  interval: 10m0s
  targetNamespace: democratic-csi
  values:
    csiDriver:
      name: org.democratic-csi.nfs
    driver:
      config:
        driver: freenas-nfs
        httpConnection:
          allowInsecure: true
          host: 192.168.19.97
          password: failfail
          port: 80
          protocol: http
          username: root
        instance_id: null
        nfs:
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareHost: 192.168.19.97
          shareMapallGroup: ""
          shareMapallUser: ""
          shareMaprootGroup: wheel
          shareMaprootUser: root
        sshConnection:
          host: 192.168.19.97
          password: failfail
          port: 22
          username: root
        zfs:
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetParentName: tank-z1/k8s/nfs/vols
          datasetPermissionsGroup: wheel
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: root
          detachedSnapshotsDatasetParentName: tank-z1/k8s/nfs/snaps
    storageClasses:
    - allowVolumeExpansion: true
      defaultClass: false
      mountOptions:
      - noatime
      - nfsvers=4
      name: freenas-nfs-csi
      parameters:
        fsType: nfs
      reclaimPolicy: Delete
      secrets:
        controller-expand-secret: null
        controller-publish-secret: null
        node-publish-secret: null
        node-stage-secret: null
        provisioner-secret: null
      volumeBindingMode: Immediate
    volumeSnapshotClasses: []

