---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todo
  namespace: flux-system
spec:
  interval: 52m31s
  path: ./kube/manifests/todo
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  validation: client

