---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 5m25s
  ref:
    branch: master
  url: https://gitlab.com/insanitywholesale/infra

