---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  interval: 3m0s
  values:
    nfs:
      path: /mnt/tank-z1/k8nfs/clusty
      reclaimPolicy: Retain
      server: 192.168.19.97
    storageClass:
      accessModes: ReadWriteOnce
      allowVolumeExpansion: true
      create: true
      defaultClass: true
      provisionerName: nfs-subdir-provis
      reclaimPolicy: Retain

