---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
  - name: core
  interval: 5m0s
  path: ./clusters/clusty/apps
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system

