---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: default-storageclass
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./kube/manifests/storageclasses
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
  validation: client

