---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  dependsOn:
  - name: core
  interval: 5m11s
  path: ./clusters/testcluster/core
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system

