nfs:
  server: 192.168.19.97
  path: "/mnt/tank-z1/k8nfs/clusty"
  reclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
#    - noatime

storageClass:
  create: true
  provisionerName: "nfs-subdir-provis"
  defaultClass: true
  allowVolumeExpansion: true
  reclaimPolicy: Retain
  accessModes: ReadWriteOnce
